pipeline {
    agent any

    stages {
        stage ('Compile Stage') {
            steps {
                    bat 'cd manager'
                    bat 'mvn clean compile'
            }
        }
        stage ('Deployment Stage') {
            steps {
                    bat 'cd manager'
                    bat 'mvn install'

            }
        }
    }
}