pipeline {
    agent any

    stages {
        stage ('Directory Stage') {

                steps {
                        sh 'cd manager'
                }
            }
        stage ('Compile Stage') {

            steps {

                    sh 'mvn clean compile'

            }
        }
        stage ('Deployment Stage') {
            steps {

                    sh 'mvn deploy'

            }
        }
    }
}