pipeline {
    agent any

    stages {
        stage ('Compile Stage') {
            steps {
                    bat 'mvn -f manager/pom.xml clean compile'
            }
        }
        stage ('Deployment Stage') {
            steps {
                    bat 'cd manager'
                    bat 'mvn -f manager/pom.xml install'

            }
        }
    }
}